In [2]:
import numpy as np

In [365]:
grid = np.array([[0,0,2,0,0,0,0,0,0],
                 [0,0,0,0,0,1,9,7,0],
                 [9,0,0,6,7,0,0,0,5],
                 [0,9,8,0,0,4,1,0,0],
                 [1,0,0,0,0,0,0,0,7],
                 [0,0,3,1,0,0,4,2,0],
                 [2,0,0,0,3,6,0,0,4],
                 [0,3,6,8,0,0,0,0,0],
                 [0,0,0,0,0,0,8,0,0]], dtype=int)

In [ ]:
def not_on_line(val,grid, ligne):
    if np.count_nonzero(grid[ligne] == val)==0:
        return True
    else:
        return False

In [319]:
def not_in_row(val,grid, col):
    if np.count_nonzero(grid[:,col] == val)==0:
        return True
    else:
        return False

In [ ]:
def not_in_square(val, grid, ligne, col):
    ligne = ligne-(ligne%3)
    col = col-(col%3)
    for ligne_c in range(ligne, ligne+3):
        for col_c in range(col, col+3):
            if (grid[ligne_c, col_c] == val):
                return False
    return True

In [352]:
def is_valid(grid,pos): 
 
    if pos == 81:
        return True
    ligne = pos//9
    col = pos%9

    if (grid[ligne,col] != 0):
        return is_valid(grid, pos+1)
   
    for k in range(1,10):
        if (not_on_line(k,grid,ligne) & not_in_row(k,grid,col) & not_in_square(k,grid,ligne, col)):
            grid[ligne,col] = k
            if ( is_valid (grid, pos+1) ):
                return True
    grid[ligne,col] = 0

    return False

In [366]:
print(grid)
print("*"*20)
is_valid(grid,0)
print(grid)

[[0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 1 9 7 0]
 [9 0 0 6 7 0 0 0 5]
 [0 9 8 0 0 4 1 0 0]
 [1 0 0 0 0 0 0 0 7]
 [0 0 3 1 0 0 4 2 0]
 [2 0 0 0 3 6 0 0 4]
 [0 3 6 8 0 0 0 0 0]
 [0 0 0 0 0 0 8 0 0]]
********************
[[8 7 2 9 5 3 6 4 1]
 [3 6 5 2 4 1 9 7 8]
 [9 4 1 6 7 8 2 3 5]
 [7 9 8 3 2 4 1 5 6]
 [1 2 4 5 6 9 3 8 7]
 [6 5 3 1 8 7 4 2 9]
 [2 8 9 7 3 6 5 1 4]
 [4 3 6 8 1 5 7 9 2]
 [5 1 7 4 9 2 8 6 3]]


In [359]:
grid

array([[8, 7, 2, 9, 5, 3, 6, 4, 1],
       [3, 6, 5, 2, 4, 1, 9, 7, 8],
       [9, 4, 1, 6, 7, 8, 2, 3, 5],
       [7, 9, 8, 3, 2, 4, 1, 5, 6],
       [1, 2, 4, 5, 6, 9, 3, 8, 7],
       [6, 5, 3, 1, 8, 7, 4, 2, 9],
       [2, 8, 9, 7, 3, 6, 5, 1, 4],
       [4, 3, 6, 8, 1, 5, 7, 9, 2],
       [5, 1, 7, 4, 9, 2, 8, 6, 3]])

===========================================================================

In [ ]:
def is_valid_old(l,c,val):     
    #print("ligne ", l, "col ", c, "val ",val)
    occurrences_lignes = np.count_nonzero(grid[l] == val)
    occurrences_colonnes = np.count_nonzero(grid[:,c] == val)

    occurrences_carre = 0
    for ligne_square in range(0,3):
        for col_square in range(0,3):
            #print(l-l%3,c-c%3)
            #print(l%3+ligne_square, c%3+col_square)
            if grid[l-l%3+ligne_square,c-c%3+col_square]==val:
                occurrences_carre+=1

    if(occurrences_lignes>1 or occurrences_colonnes>1 or occurrences_carre>1):
        return False
    else:
        return True
            

In [107]:
def get_possible_numbers(l,c):
    val = []
    for i in range(1,10):        
        not_in_ligne = not (i in grid[l])
        not_in_col =   not (i in grid[:,c])

        not_in_square = True
        for ligne_square in range(0,2):
            for col_square in range(0,2):
                if grid[l%3+ligne_square,c%3+col_square]==i:
                    not_in_square= False

        if(not_in_ligne  & not_in_col & not_in_square):
            val.append(i)
    cells.append([l,c,val])
    return val
        

In [116]:
cells = []

for ligne in range(0,9):
    for colonne in range(0,9):
        val = grid[ligne,colonne]
        if val==0:
            possibles = get_possible_numbers(ligne, colonne)
            if len(possibles)==1:
                print(ligne, colonne, possibles[0])
                grid[ligne,colonne]=possibles[0]
            